//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemAdmin.Localization.FormBusiness.FormWorkflow {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemAdmin.Localization.FormBusiness.FormWorkflow.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 签核最高上限删除失败 的本地化字符串。
        /// </summary>
        public static string FormReviewLimitDeleteFailed {
            get {
                return ResourceManager.GetString("FormReviewLimitDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签核最高上限删除成功 的本地化字符串。
        /// </summary>
        public static string FormReviewLimitDeleteSuccess {
            get {
                return ResourceManager.GetString("FormReviewLimitDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签核最高上限新增失败 的本地化字符串。
        /// </summary>
        public static string FormReviewLimitInsertFailed {
            get {
                return ResourceManager.GetString("FormReviewLimitInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签核最高上限新增成功 的本地化字符串。
        /// </summary>
        public static string FormReviewLimitInsertSuccess {
            get {
                return ResourceManager.GetString("FormReviewLimitInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职级已有最高上限配置，请勿重复配置 的本地化字符串。
        /// </summary>
        public static string FormReviewLimitRepeat {
            get {
                return ResourceManager.GetString("FormReviewLimitRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签核最高上限修改失败 的本地化字符串。
        /// </summary>
        public static string FormReviewLimitUpdateFailed {
            get {
                return ResourceManager.GetString("FormReviewLimitUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签核最高上限修改成功 的本地化字符串。
        /// </summary>
        public static string FormReviewLimitUpdateSuccess {
            get {
                return ResourceManager.GetString("FormReviewLimitUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分支删除失败 的本地化字符串。
        /// </summary>
        public static string WorkflowBranchDeleteFailed {
            get {
                return ResourceManager.GetString("WorkflowBranchDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分支删除成功 的本地化字符串。
        /// </summary>
        public static string WorkflowBranchDeleteSuccess {
            get {
                return ResourceManager.GetString("WorkflowBranchDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分支新增失败 的本地化字符串。
        /// </summary>
        public static string WorkflowBranchInsertFailed {
            get {
                return ResourceManager.GetString("WorkflowBranchInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分支新增成功 的本地化字符串。
        /// </summary>
        public static string WorkflowBranchInsertSuccess {
            get {
                return ResourceManager.GetString("WorkflowBranchInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分支已配置相关步骤，请先删除所有对应步骤 的本地化字符串。
        /// </summary>
        public static string WorkflowBranchNotDelete {
            get {
                return ResourceManager.GetString("WorkflowBranchNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分支修改失败 的本地化字符串。
        /// </summary>
        public static string WorkflowBranchUpdateFailed {
            get {
                return ResourceManager.GetString("WorkflowBranchUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分支修改成功 的本地化字符串。
        /// </summary>
        public static string WorkflowBranchUpdateSuccess {
            get {
                return ResourceManager.GetString("WorkflowBranchUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则删除失败 的本地化字符串。
        /// </summary>
        public static string WorkflowRuleDeleteFailed {
            get {
                return ResourceManager.GetString("WorkflowRuleDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则删除成功 的本地化字符串。
        /// </summary>
        public static string WorkflowRuleDeleteSuccess {
            get {
                return ResourceManager.GetString("WorkflowRuleDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则新增失败 的本地化字符串。
        /// </summary>
        public static string WorkflowRuleInsertFailed {
            get {
                return ResourceManager.GetString("WorkflowRuleInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则新增成功 的本地化字符串。
        /// </summary>
        public static string WorkflowRuleInsertSuccess {
            get {
                return ResourceManager.GetString("WorkflowRuleInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已有对应条件的规则，请勿重复配置 的本地化字符串。
        /// </summary>
        public static string WorkflowRuleRepat {
            get {
                return ResourceManager.GetString("WorkflowRuleRepat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则修改失败 的本地化字符串。
        /// </summary>
        public static string WorkflowRuleUpdateFailed {
            get {
                return ResourceManager.GetString("WorkflowRuleUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则修改成功 的本地化字符串。
        /// </summary>
        public static string WorkflowRuleUpdateSuccess {
            get {
                return ResourceManager.GetString("WorkflowRuleUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤删除失败 的本地化字符串。
        /// </summary>
        public static string WorkflowStepDeleteFailed {
            get {
                return ResourceManager.GetString("WorkflowStepDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤删除成功 的本地化字符串。
        /// </summary>
        public static string WorkflowStepDeleteSuccess {
            get {
                return ResourceManager.GetString("WorkflowStepDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤新增失败 的本地化字符串。
        /// </summary>
        public static string WorkflowStepInsertFailed {
            get {
                return ResourceManager.GetString("WorkflowStepInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤新增成功 的本地化字符串。
        /// </summary>
        public static string WorkflowStepInsertSuccess {
            get {
                return ResourceManager.GetString("WorkflowStepInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤修改失败 的本地化字符串。
        /// </summary>
        public static string WorkflowStepUpdateFailed {
            get {
                return ResourceManager.GetString("WorkflowStepUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤修改成功 的本地化字符串。
        /// </summary>
        public static string WorkflowStepUpdateSuccess {
            get {
                return ResourceManager.GetString("WorkflowStepUpdateSuccess", resourceCulture);
            }
        }
    }
}
