//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemAdmin.Localization.FormBusiness.FormWorkflow {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemAdmin.Localization.FormBusiness.FormWorkflow.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 分支删除失败 的本地化字符串。
        /// </summary>
        public static string WorkflowBranchDeleteFailed {
            get {
                return ResourceManager.GetString("WorkflowBranchDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分支删除成功 的本地化字符串。
        /// </summary>
        public static string WorkflowBranchDeleteSuccess {
            get {
                return ResourceManager.GetString("WorkflowBranchDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分支新增失败 的本地化字符串。
        /// </summary>
        public static string WorkflowBranchInsertFailed {
            get {
                return ResourceManager.GetString("WorkflowBranchInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分支新增成功 的本地化字符串。
        /// </summary>
        public static string WorkflowBranchInsertSuccess {
            get {
                return ResourceManager.GetString("WorkflowBranchInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分支已有对应步骤，请先删除所有对应步骤 的本地化字符串。
        /// </summary>
        public static string WorkflowBranchNotDelete {
            get {
                return ResourceManager.GetString("WorkflowBranchNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分支步骤删除失败 的本地化字符串。
        /// </summary>
        public static string WorkflowBranchStepDeleteFailed {
            get {
                return ResourceManager.GetString("WorkflowBranchStepDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分支步骤删除成功 的本地化字符串。
        /// </summary>
        public static string WorkflowBranchStepDeleteSuccess {
            get {
                return ResourceManager.GetString("WorkflowBranchStepDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分支步骤新增失败 的本地化字符串。
        /// </summary>
        public static string WorkflowBranchStepInsertFailed {
            get {
                return ResourceManager.GetString("WorkflowBranchStepInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分支步骤新增成功 的本地化字符串。
        /// </summary>
        public static string WorkflowBranchStepInsertSuccess {
            get {
                return ResourceManager.GetString("WorkflowBranchStepInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请勿重复配置分支步骤 的本地化字符串。
        /// </summary>
        public static string WorkflowBranchStepIsRepat {
            get {
                return ResourceManager.GetString("WorkflowBranchStepIsRepat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分支步骤修改失败 的本地化字符串。
        /// </summary>
        public static string WorkflowBranchStepUpdateFailed {
            get {
                return ResourceManager.GetString("WorkflowBranchStepUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分支步骤修改成功 的本地化字符串。
        /// </summary>
        public static string WorkflowBranchStepUpdateSuccess {
            get {
                return ResourceManager.GetString("WorkflowBranchStepUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分支修改失败 的本地化字符串。
        /// </summary>
        public static string WorkflowBranchUpdateFailed {
            get {
                return ResourceManager.GetString("WorkflowBranchUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分支修改成功 的本地化字符串。
        /// </summary>
        public static string WorkflowBranchUpdateSuccess {
            get {
                return ResourceManager.GetString("WorkflowBranchUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤删除失败 的本地化字符串。
        /// </summary>
        public static string WorkflowStepDeleteFailed {
            get {
                return ResourceManager.GetString("WorkflowStepDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤删除成功 的本地化字符串。
        /// </summary>
        public static string WorkflowStepDeleteSuccess {
            get {
                return ResourceManager.GetString("WorkflowStepDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤新增失败 的本地化字符串。
        /// </summary>
        public static string WorkflowStepInsertFailed {
            get {
                return ResourceManager.GetString("WorkflowStepInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤新增成功 的本地化字符串。
        /// </summary>
        public static string WorkflowStepInsertSuccess {
            get {
                return ResourceManager.GetString("WorkflowStepInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤修改失败 的本地化字符串。
        /// </summary>
        public static string WorkflowStepUpdateFailed {
            get {
                return ResourceManager.GetString("WorkflowStepUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤修改成功 的本地化字符串。
        /// </summary>
        public static string WorkflowStepUpdateSuccess {
            get {
                return ResourceManager.GetString("WorkflowStepUpdateSuccess", resourceCulture);
            }
        }
    }
}
