﻿//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemAdmin.Localization.SystemBasicMgmt.UserSettings {
    using System;

    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp =
                        new global::System.Resources.ResourceManager("SystemAdmin.Localization.SystemBasicMgmt.SystemConfig.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 被代理员工不能与代理员工相同。 的本地化字符串。
        /// </summary>
        public static string UserAgentSubAgentSameAsAgent {
            get {
                return ResourceManager.GetString("UserAgentSubAgentSameAsAgent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 该代理关系已存在。 的本地化字符串。
        /// </summary>
        public static string UserAgentRelationAlreadyExist {
            get {
                return ResourceManager.GetString("UserAgentRelationAlreadyExist", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 被代理员工已作为其他员工的代理人，无法重复设置。 的本地化字符串。
        /// </summary>
        public static string UserAgentSubAgentAlreadyAgent {
            get {
                return ResourceManager.GetString("UserAgentSubAgentAlreadyAgent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 代理员工已作为其他员工的被代理人，无法重复设置。 的本地化字符串。
        /// </summary>
        public static string UserAgentAgentAlreadySubAgent {
            get {
                return ResourceManager.GetString("UserAgentAgentAlreadySubAgent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 代理配置成功。 的本地化字符串。
        /// </summary>
        public static string UserAgentInsertSuccess {
            get {
                return ResourceManager.GetString("UserAgentInsertSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 代理配置失败。 的本地化字符串。
        /// </summary>
        public static string UserAgentInsertFailed {
            get {
                return ResourceManager.GetString("UserAgentInsertFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 代理关系删除成功。 的本地化字符串。
        /// </summary>
        public static string UserAgentDeleteSuccess {
            get {
                return ResourceManager.GetString("UserAgentDeleteSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 代理关系删除失败。 的本地化字符串。
        /// </summary>
        public static string UserAgentDeleteFailed {
            get {
                return ResourceManager.GetString("UserAgentDeleteFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 员工兼任新增成功。 的本地化字符串。
        /// </summary>
        public static string UserPartTimeInsertSuccess {
            get {
                return ResourceManager.GetString("UserPartTimeInsertSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 员工兼任新增失败。 的本地化字符串。
        /// </summary>
        public static string UserPartTimeInsertFailed {
            get {
                return ResourceManager.GetString("UserPartTimeInsertFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 员工兼任删除成功。 的本地化字符串。
        /// </summary>
        public static string UserPartTimeDeleteSuccess {
            get {
                return ResourceManager.GetString("UserPartTimeDeleteSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 员工兼任删除失败。 的本地化字符串。
        /// </summary>
        public static string UserPartTimeDeleteFailed {
            get {
                return ResourceManager.GetString("UserPartTimeDeleteFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 该员工已在此部门兼任该职业，无法重复设置。 的本地化字符串。
        /// </summary>
        public static string UserPartTimeIsExist {
            get {
                return ResourceManager.GetString("UserPartTimeIsExist", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 员工兼任修改成功。 的本地化字符串。
        /// </summary>
        public static string UserPartTimeUpdateSuccess {
            get {
                return ResourceManager.GetString("UserPartTimeUpdateSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 员工兼任修改失败。 的本地化字符串。
        /// </summary>
        public static string UserPartTimeUpdateFailed {
            get {
                return ResourceManager.GetString("UserPartTimeUpdateFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 表单配置成功。 的本地化字符串。
        /// </summary>
        public static string UserFormBindInsertSuccess {
            get {
                return ResourceManager.GetString("UserFormBindInsertSuccess", resourceCulture);
            }
        }
    }
}
