//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemAdmin.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemAdmin.Localization.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 账号密码错误，剩余 {0} 次机会 的本地化字符串。
        /// </summary>
        public static string SystemBasicMgmt_Auth_SysLogOut_LoginFailed {
            get {
                return ResourceManager.GetString("SystemBasicMgmt_Auth_SysLogOut_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录成功！ 的本地化字符串。
        /// </summary>
        public static string SystemBasicMgmt_Auth_SysLogOut_LoginSuccess {
            get {
                return ResourceManager.GetString("SystemBasicMgmt_Auth_SysLogOut_LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该帐号已锁定，请解锁 的本地化字符串。
        /// </summary>
        public static string SystemBasicMgmt_SystemBasicCoreApi_SysLogOut_LoginLock {
            get {
                return ResourceManager.GetString("SystemBasicMgmt_SystemBasicCoreApi_SysLogOut_LoginLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安全登出失败！ 的本地化字符串。
        /// </summary>
        public static string SystemBasicMgmt_SystemBasicCoreApi_SysLogOut_LogOutFailed {
            get {
                return ResourceManager.GetString("SystemBasicMgmt_SystemBasicCoreApi_SysLogOut_LogOutFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安全登出成功！ 的本地化字符串。
        /// </summary>
        public static string SystemBasicMgmt_SystemBasicCoreApi_SysLogOut_LogOutSuccess {
            get {
                return ResourceManager.GetString("SystemBasicMgmt_SystemBasicCoreApi_SysLogOut_LogOutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号密码已过期，请及时修改 的本地化字符串。
        /// </summary>
        public static string SystemBasicMgmt_SystemBasicCoreApi_SysLogOut_PasswordExpiration {
            get {
                return ResourceManager.GetString("SystemBasicMgmt_SystemBasicCoreApi_SysLogOut_PasswordExpiration", resourceCulture);
            }
        }
    }
}
