﻿//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemAdmin.Localization.SystemBasicMgmt.SystemConfig {
    using System;

    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp =
                        new global::System.Resources.ResourceManager("SystemAdmin.Localization.SystemBasicMgmt.SystemConfig.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 系统字典新增成功。 的本地化字符串。
        /// </summary>
        public static string DictionaryInfoInsertSuccess {
            get {
                return ResourceManager.GetString("DictionaryInfoInsertSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 系统字典新增失败。 的本地化字符串。
        /// </summary>
        public static string DictionaryInfoInsertFailed {
            get {
                return ResourceManager.GetString("DictionaryInfoInsertFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 系统字典删除成功。 的本地化字符串。
        /// </summary>
        public static string DictionaryInfoDeleteSuccess {
            get {
                return ResourceManager.GetString("DictionaryInfoDeleteSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 系统字典删除失败。 的本地化字符串。
        /// </summary>
        public static string DictionaryInfoDeleteFailed {
            get {
                return ResourceManager.GetString("DictionaryInfoDeleteFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 系统字典修改成功。 的本地化字符串。
        /// </summary>
        public static string DictionaryInfoUpdateSuccess {
            get {
                return ResourceManager.GetString("DictionaryInfoUpdateSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 系统字典修改失败。 的本地化字符串。
        /// </summary>
        public static string DictionaryInfoUpdateFailed {
            get {
                return ResourceManager.GetString("DictionaryInfoUpdateFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 该字典类型下已存在相同的字典编码。 的本地化字符串。
        /// </summary>
        public static string DictionaryInfoDicTypeCodeIsExist {
            get {
                return ResourceManager.GetString("DictionaryInfoDicTypeCodeIsExist", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 币别信息新增成功。 的本地化字符串。
        /// </summary>
        public static string CurrencyInfoInsertSuccess {
            get {
                return ResourceManager.GetString("CurrencyInfoInsertSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 币别信息新增失败。 的本地化字符串。
        /// </summary>
        public static string CurrencyInfoInsertFailed {
            get {
                return ResourceManager.GetString("CurrencyInfoInsertFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 币别信息删除成功。 的本地化字符串。
        /// </summary>
        public static string CurrencyInfoDeleteSuccess {
            get {
                return ResourceManager.GetString("CurrencyInfoDeleteSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 币别信息删除失败。 的本地化字符串。
        /// </summary>
        public static string CurrencyInfoDeleteFailed {
            get {
                return ResourceManager.GetString("CurrencyInfoDeleteFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 币别信息修改成功。 的本地化字符串。
        /// </summary>
        public static string CurrencyInfoUpdateSuccess {
            get {
                return ResourceManager.GetString("CurrencyInfoUpdateSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 币别信息修改失败。 的本地化字符串。
        /// </summary>
        public static string CurrencyInfoUpdateFailed {
            get {
                return ResourceManager.GetString("CurrencyInfoUpdateFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 汇率信息新增成功。 的本地化字符串。
        /// </summary>
        public static string ExchangeRateInsertSuccess {
            get {
                return ResourceManager.GetString("ExchangeRateInsertSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 汇率信息新增失败。 的本地化字符串。
        /// </summary>
        public static string ExchangeRateInsertFailed {
            get {
                return ResourceManager.GetString("ExchangeRateInsertFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 汇率信息删除成功。 的本地化字符串。
        /// </summary>
        public static string ExchangeRateDeleteSuccess {
            get {
                return ResourceManager.GetString("ExchangeRateDeleteSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 汇率信息删除失败。 的本地化字符串。
        /// </summary>
        public static string ExchangeRateDeleteFailed {
            get {
                return ResourceManager.GetString("ExchangeRateDeleteFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 汇率信息修改成功。 的本地化字符串。
        /// </summary>
        public static string ExchangeRateUpdateSuccess {
            get {
                return ResourceManager.GetString("ExchangeRateUpdateSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 汇率信息修改失败。 的本地化字符串。
        /// </summary>
        public static string ExchangeRateUpdateFailed {
            get {
                return ResourceManager.GetString("ExchangeRateUpdateFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 该币别汇率对照已存在。 的本地化字符串。
        /// </summary>
        public static string ExchangeRateIsExist {
            get {
                return ResourceManager.GetString("ExchangeRateIsExist", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 币别不能与兑换币别相同。 的本地化字符串。
        /// </summary>
        public static string ExchangeRateIsRepeat {
            get {
                return ResourceManager.GetString("ExchangeRateIsRepeat", resourceCulture);
            }
        }
    }
}
